steps:

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://dpf-secrets/credentials.json.enc', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=credentials.json.enc
  - --plaintext-file=credentials.json
  - --location=global
  - --keyring=guillaume
  - --key=test

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', '-w', '/data', '-v', '/workspace:/data', '--env', 'GOOGLE_APPLICATION_CREDENTIALS=credentials.json', 'hashicorp/terraform', 'init' ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', '-w', '/data', '-v', '/workspace:/data', '--env', 'GOOGLE_APPLICATION_CREDENTIALS=credentials.json', 'hashicorp/terraform', 'plan' ]

#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform', '.']

#- name: ubuntu
#  args: ['ls']
